#!/bin/sh

setxkbmap br
setxkbmap -option caps:ctrl_modifier

xrdb $HOME/.Xresources

xwallpaper --zoom $HOME/pictures/wallpapers/GhibliFull.png

xset s off -dpms

xmodmap -e "pointer = 3 2 1"

xbanish &

sxhkd &

picom &

pgrep -x -t $(tty) notdaemon >> /dev/null || notdaemon &
pgrep -x -t $(tty) dwmblocks >> /dev/null || dwmblocks &

dwm
