#!/bin/sh

setxkbmap -option compose:ralt

xrdb "$HOME/.Xresources"

xwallpaper --zoom "$HOME/pictures/wallpapers/ghibli.png"

xset s off -dpms

exec picom &

exec urxvtd -q -f -o &

exec dunst &

xmonad >/dev/null 2>&1
